apiVersion: v1
kind: Service
metadata:
  name: nodeapp-db-service
spec:
  selector:
    app: nodeapp
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nodeapp-db
spec:
  serviceName: nodeapp-db-service
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
      role: db
  template:
    metadata:
      labels:
        app: nodeapp
        role: db
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: Frds@1234567890
            - name: POSTGRES_DB
              value: node_db
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-data
          emptyDir: {}
